### ISSUE TITLE
Создать верстку страниц пятого дня

### ISSUE THREAD

**Issue by Jeobaz** [Jeobaz/marathon-se#15]

**Comment by Jeobaz** [comment]
- [x] 5.3 CREATE “23. MANAGE A RUNNER”
- [x] 5.4 CREATE “24. EDIT RUNNER PROFILE”
- [x] 5.5 CREATE “25. CERTIFICATE PREVIEW”
- [x] 5.6 CREATE “21. SPONSORSHIP OVERVIEW”

**Comment by shigomany** [comment]
Нету 25 формы
